### ISSUE TITLE
Missing requirement Cryptodome?

### ISSUE THREAD

**Issue by freol35241** [Ernst79/bleparser#11]
When installing this package from pypi (```pip install bleparser```) the Cryptodome package does not get installed, which seems to be a hard requirement (https://github.com/Ernst79/bleparser/blob/master/package/bleparser/xiaomi.py#L5).

Should be added into ```setup.cfg``` under "install_requires".

I would be happy to draft a PR for this, but a little unsure about the requirements_test.txt in this repo which specifies a specific version of Cryptodome. Any particular reason for pinning the version or would any version >3 be ok?

**Comment by Ernst79** [comment]
I was under the impression that `packages = find:` would take care of that, but apparently not. 

Any version of Cryptodome is ok, using the latest would be preferred, I think.
