### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by Benny2102** [Ernst79/bleparser#23]
Hello!
I use pi zero. Would anyone help with the installation? How to set up? I want to transfer data from Xiaomi and iNode devices to a more remote Home Assistant server.

**Comment by Ernst79** [comment]
Sorry, I missed your question. There are two options, I think. 

1. Use ESPhome with BLE gateway, as described here: https://custom-components.github.io/ble_monitor/parse_data. This will collect the raw BLE data with an ESP device and will forward it over WiFi to your remote Home Assistant server with BLE monitor. The HA server (BLE monitor) will take care of the translation from the RAW message to a HA sensors. 
2. Set up a second HA machine with Bluetooth, and use remote Home Assistant to link the two Home Assistant servers: https://github.com/custom-components/remote_homeassistant With this method, one HA server will take care of the translation of the RAW data to HA sensors, and remote Home Assistant will take care of forwarding the sensor data to your remote Home Assistant server. 

Note that not all raspberry zero's have Bluetooth. I think the zero 2 W does have it. Is you haven't bought a device yet, I would go the ESPhome route.
